version: '2'

services:
  backend-server:
    container_name: matusek-solutions-backend-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - JWT_SECRET=secret321