server:
  port: 8761

spring:
  application:
    name: "discovery-server"
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false