server:
  port: 9002

spring:
  application:
    name: "authentication-service"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

solutions:
  matusek:
    jwt:
      issuer: "solutions.matusek"
      algorithm: "RSA"
      keySize: 2048
      expirationSeconds: 3600
    keyStore:
      filePath: "/Users/matusek/Workplace/MatusekSolutions/OtherFiles/KeyStore/microservicesapp-keystore"
      password: "Soonr123"
      type: "JKS"
    certificate:
      alias: "matusek.solutions"
      password: "aaa111"
      algorithm: "RSA"
      keySize: 2048