spring:
  application:
    name: "discovery-service"
  cloud:
    config:
      server:
        git:
          uri: "C:\\Users\\matusek\\Workspace\\Training\\SpringMIcroservicesPrototype\\config-repository"

server:
  port: 8888