version: '2'

services:
  frontend-client:
    container_name: matusek-solutions-frontend-client
    build:
      context: ../frontend-client
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - JWT_SECRET=secret321